# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 vmImage: 'ubuntu-20.04'

stages:
- stage: 'Build'
  displayName: 'Build the application'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    steps:
    - task: CmdLine@2
      inputs:
        script: 'echo build job' 
      displayName: "Building Game"

- stage: 'dev'
  dependsOn: 'Build'
  displayName: 'Build dev stage'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    steps:
    - task: CmdLine@2
      inputs:
        script: 'echo dev job' 
      displayName: "Building Game"

- stage: 'int'
  dependsOn: 'Build'
  displayName: 'Build int stage'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    steps:
    - task: CmdLine@2
      inputs:
        script: 'echo int job' 
      displayName: "Building Game"

- stage: 'stg'
  dependsOn: 'Build'
  displayName: 'Build stg stage'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    steps:
    - task: CmdLine@2
      inputs:
        script: 'echo stg job' 
      displayName: "Building Game"