# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

stages:
- stage: 'Build'
  displayName: 'Build the application'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          "C:\Program Files\Unity\Hub\Editor\2020.2.0b14\Editor\Unity.exe" -quit -batchmode -projectPath ".\Game" -executeMethod CustomBuild.BuildAndRun
      displayName: "Building Game"

- stage: 'dev'
  displayName: 'Build dev stage'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          "C:\Program Files\Unity\Hub\Editor\2020.2.0b14\Editor\Unity.exe" -quit -batchmode -projectPath ".\Game" -executeMethod CustomBuild.BuildAndRun
      displayName: "Building Game"

- stage: 'int'
  displayName: 'Build int stage'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          "C:\Program Files\Unity\Hub\Editor\2020.2.0b14\Editor\Unity.exe" -quit -batchmode -projectPath ".\Game" -executeMethod CustomBuild.BuildAndRun
      displayName: "Building Game"

- stage: 'stg'
  displayName: 'Build stg stage'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          "C:\Program Files\Unity\Hub\Editor\2020.2.0b14\Editor\Unity.exe" -quit -batchmode -projectPath ".\Game" -executeMethod CustomBuild.BuildAndRun
      displayName: "Building Game"