# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 vmImage: 'ubuntu-20.04'

variables:
- group: EnvVersions

stages:
- stage: 'Build'
  displayName: 'Build the application'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    steps:
    - task: CmdLine@2
      inputs:
        script: echo variables['Build.SourceBranch'] 
      displayName: "Building Game"

- stage: 'dev'
  dependsOn: 'Build'
  condition:  eq(variables['Build.SourceBranch'], 'master')
  displayName: 'Build dev stage'
  jobs:
  - deployment: 'dev'
    displayName: 'Build job'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: 'echo deploying dev...'

- stage: 'int'
  dependsOn: 'Build'
  displayName: 'Build dev stage'
  jobs:
  - deployment: 'dev'
    displayName: 'Build job'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: 'echo deploying int...'

- stage: 'stg'
  dependsOn: 'Build'
  displayName: 'Build dev stage'
  jobs:
  - deployment: 'dev'
    displayName: 'Build job'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: 'echo deploying stg...'